version: 3.8

services:
  ingestion:
    build: .
    target: deploy
    links:
      storage_emulator
    depends_on:
      storage_emulator
    environment:
      STORAGE_HOST: storage_emulator
      STORAGE_PORT: 9023
      STORAGE_BUCKET_NAME: earthquake_bucket
  storage_emulator:
    image: oittaa/gcp-storage-emulator
    entrypoint: gcp-storage-emulator start --host=localhost --port=9023 --default-bucket=earthquake_bucket
    volumes:
      ./storage:/.cloudstorage