version: "3.8"

services:
  ingestion:
    build:
      context: .
      target: deploy
    links:
      - storage_emulator
    depends_on:
      - storage_emulator
    environment:
      STORAGE_EMULATOR_HOST="https://storage_emulator:9023"
  storage_emulator:
    image: oittaa/gcp-storage-emulator
    entrypoint: gcp-storage-emulator start --host=localhost --port=9023 --default-bucket=earthquake_bucket
    volumes:
      - ./.storage:/.cloudstorage