name: Ruff

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: install dependancies
      run: |
        pip install -r requirements.txt
        pip install ruff
    - name: lint file
      run: ruff check --fix .
    - name: reformat code
      run: ruff format .
    
    - name: set user
      run: |
        git config --global user.name 'auto_linter_action'
        git config --global user.email 'felixroland12355@users.noreply.github.com'
    - name: check changes
      run: git status
    - name: stage change
      run: git add .
    - name: commit changes
      run: git commit -m "Automatic Code Formatting"
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}
        directory: .
      
